#!/bin/sh
echo "ipfs-follower postinst executing"

rm -rf ~/.ipfs
ipfs init
ipfs config profile apply flatfs
# should reduce bandwidth utilization some
ipfs config profile apply lowpower
# disable mdns discovery. good for ipv4 hosts
ipfs config profile apply server
# helium uses port 8080
sed -i s/8080/8081/ ~/.ipfs/config
# force QUIC. QUIC and TCP are enabled by default. set TCP to false. will reduce bandwith
sed -i 's/"Network": {}/"Network": {"TCP": false}/' ~/.ipfs/config

# create a semi-private network (privacy not enforced by a swarm key)
# if a swarm key is used, need to also export LIBP2P_FORCE_PNET=1
ipfs bootstrap rm --all
ipfs bootstrap add /ip4/$ADDRESS_FOR_IPFS_LEADER_BOOTSTRAP_NODE/udp/4001/quic/p2p/$KEY_FOR_IPFS_LEADER_BOOTSTRAP_NODE

if [ -e /proc/1/root/. ] && [ "$(stat -c %d:%i /)" = "$(stat -c %d:%i /proc/1/root/.)" ]; then
    echo "Starting service..."
    systemctl daemon-reload
    systemctl start ipfs
fi

systemctl enable ipfs
