name: build-ipfs-leader-arm64

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.11
      - name: build
        run: |
          echo "deb [arch=arm64] http://ports.ubuntu.com/ bionic main multiverse restricted universe" | sudo tee /etc/apt/sources.list.d/arm46-sources.list
          sudo apt-get update 
          sudo apt purge libssl1.0.0 libssl1.1 libssl-dev
          sudo apt-get install -y gcc-8-aarch64-linux-gnu libssl-dev:arm64
          git clone --depth 1 --branch v0.12.2 https://github.com/ipfs/go-ipfs.git
          cd go-ipfs
          export CC=aarch64-linux-gnu-gcc-8
          make build GOOS=linux GOARCH=arm64 GOTAGS=openssl CGO_ENABLED=1
      - uses: actions/upload-artifact@v2
        with:
          name: ipfs
          path: go-ipfs/cmd/ipfs/ipfs
  package:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: ipfs
      - uses: kentik/pkg@v1.0.0-rc8
        with:
          name: ipfs
          version: 0.12.2
          arch: arm64
          format: deb
          package: ipfs-leader-package.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: ipfs_0.12.2-1_arm64.deb
          path: ipfs_0.12.2-1_arm64.deb
