name: ipfs-cluster-arm64

on:
  push:
    branches:
        - main

env:
  IPFS_CLUSTER_VERSION: 1.0.1
  PACKAGE_NAME: ipfs-cluster
  PACKAGE_VERSION: 1.0.1
  PACKAGE_REVISION: 1
  PACKAGE_ARCHITECTURE: arm64

jobs:
  build-package-upload:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.11
      - name: build-and-package
        run: |
          sudo mkdir -p /usr/include/aarch64-linux-gnu/openssl
          sudo cp libssl-dev_arm64/usr/include/aarch64-linux-gnu/openssl/opensslconf.h /usr/include/aarch64-linux-gnu/openssl/opensslconf.h
          sudo cp -r libssl-dev_arm64/usr/lib/aarch64-linux-gnu /usr/lib/
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          git clone --depth 1 --branch v${{ env.IPFS_CLUSTER_VERSION }} https://github.com/ipfs/ipfs-cluster.git
          export CC=aarch64-linux-gnu-gcc
          make -C ipfs-cluster build GOOS=linux GOARCH=arm64 GOTAGS=openssl CGO_ENABLED=1
          cp ipfs-cluster/cmd/ipfs-cluster-service/ipfs-cluster-service ipfs-cluster-deb/input/
          cp ipfs-cluster/cmd/ipfs-cluster-ctl/ipfs-cluster-ctl ipfs-cluster-deb/input/
          cd ipfs-cluster-deb
          ./package.sh ${{ env.PACKAGE_NAME }} ${{ env.PACKAGE_VERSION }} ${{ env.PACKAGE_REVISION }} ${{ env.PACKAGE_ARCHITECTURE }}
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}-${{ env.PACKAGE_REVISION }}_${{ env.PACKAGE_ARCHITECTURE }}.deb
          path: ipfs-cluster-deb/output/build/${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}-${{ env.PACKAGE_REVISION }}_${{ env.PACKAGE_ARCHITECTURE }}.deb
