name: ipfs-leader-amd64

on: [workflow_dispatch]

env:
  IPFS_VERSION: 0.12.2
  PACKAGE_NAME: ipfs-leader
  PACKAGE_VERSION: 0.12.2
  PACKAGE_REVISION: 1
  PACKAGE_ARCHITECTURE: amd64

jobs:
  build-package-upload:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.11
      - name: build-and-package
        run: |
          cd ipfs-deb/ipfs-leader/amd64
          ./build.sh ${{ env.IPFS_VERSION }}
          ./package.sh ${{ env.PACKAGE_NAME }} ${{ env.PACKAGE_VERSION }} ${{ env.PACKAGE_REVISION }} ${{ env.PACKAGE_ARCHITECTURE }}
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}-${{ env.PACKAGE_REVISION }}_${{ env.PACKAGE_ARCHITECTURE }}.deb
          path: ipfs-deb/ipfs-leader/amd64/output/build/${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}-${{ env.PACKAGE_REVISION }}_${{ env.PACKAGE_ARCHITECTURE }}.deb
