name: build-ipfs-leader-amd64

on:
  push:
    branches:
        - main

env:
  IPFS_VERSION: 0.12.2

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.11
      - name: build
        run: |
          git clone --depth 1 --branch v${{ env.IPFS_VERSION }} https://github.com/ipfs/go-ipfs.git
          cd go-ipfs
          make build
      - uses: actions/upload-artifact@v2
        with:
          name: ipfs
          path: go-ipfs/cmd/ipfs/ipfs
  package:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: ipfs
      - uses: kentik/pkg@v1.0.0-rc8
        with:
          name: ipfs
          version: ${{ env.IPFS_VERSION }}
          arch: amd64
          format: deb
          package: ipfs-leader-package.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: ipfs_${{ env.IPFS_VERSION }}-1_amd64.deb
          path: ipfs_${{ env.IPFS_VERSION }}-1_amd64.deb
